export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const VISIBILITY_FILTER = "VISIBILITY_FILTER";
export const DISPLAY_TODOS = "DISPLAY_TODOS";
export const LOADING = "LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const DISPLAY_ERROR = "DISPLAY_ERROR";
